---
title: "Assignment B4 Shiny App"
output: github_document
---

# An application to explore the gapminder dataset

This is an assignment B4 completed for UBC Stat 545B course. 
This app is not an extension of the BCL app submitted to assignment B3; this has been started from scratch.

The application explores the gapminder dataset contained in the gapminder package (https://cran.r-project.org/web/packages/gapminder/README.html)

The app can be found at https://britttheuser.shinyapps.io/GapminderApp/

## Here are the functionalities of the current app:
1. The application theme is set to be darkly
2. User can choose the continent then the country they wish to see the data of, the country drop down menu reacts to the continent choice
3. A slider is available to restrict the year range of output and a drop down menu for the variable to be compared over the years
4. A plot and a table will be generated from the above selections (2 & 3) in separate tabs
5. Radio buttons are also available to see overviews by continent (mean of all countries within the chosen continent)
6. A tab to for users to type in the country name to view the information for a specific country
